/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppCustomLogo: typeof import('./src/components/AppCustomLogo.vue')['default']
    BaseBlogCard: typeof import('./src/components/BaseBlogCard.vue')['default']
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    BlogImage: typeof import('./src/components/BlogImage.vue')['default']
    BlogInfo: typeof import('./src/components/BlogInfo.vue')['default']
    FeaturedBlog: typeof import('./src/components/FeaturedBlog.vue')['default']
    HelloWorld: typeof import('./src/components/blog/HelloWorld.vue')['default']
    PinnedBlog: typeof import('./src/components/PinnedBlog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
