/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/app/AppBar.vue')['default']
    AppCustomLogo: typeof import('./components/app/AppCustomLogo.vue')['default']
    BaseBlogCard: typeof import('./components/blog/BaseBlogCard.vue')['default']
    BlogCard: typeof import('./components/blog/BlogCard.vue')['default']
    BlogImage: typeof import('./components/blog/BlogImage.vue')['default']
    BlogInfo: typeof import('./components/blog/BlogInfo.vue')['default']
    FeaturedBlog: typeof import('./components/blog/FeaturedBlog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PinnedBlog: typeof import('./components/blog/PinnedBlog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
